Django 4 support
namespace-ee/drf-sideloading pull request #49
Opened 2024-01-26 14:47 UTC by tonisvain

Add support for Django 4

2024-07-19 09:20 UTC, lnagel requested changes, later dismissed
Added notes

2024-07-19 09:20 UTC, lnagel commented on drf_sideloading/mixins.py
> +                # FIXME: apply filtering here!
FIXME: apply filtering here!

2024-07-19 09:20 UTC, lnagel commented on drf_sideloading/mixins.py
> +            # fixme: Check if different filters where applied to Prefetch queryset.
# fixme: Check if different filters where applied to Prefetch queryset.

2024-07-19 09:20 UTC, lnagel commented on tests/test_products_api.py
>          # FIXME: the Prefetch does not filter the queryset as expected!
FIXME: the Prefetch does not filter the queryset as expected!

2024-10-23 13:28 UTC, tonisvain commented
@lnagel 
before realease, lets go over the changelog and versioning. 
As there where multiple PR-s that where originally supposed to be separate versions but they got merged togetkelr because of the big refactor, we might want to merge the changelog also and just release it as version 2.1.0 ?

2024-10-25 09:39 UTC, merged